input.onButtonPressed(Button.A, function () {
    basic.showIcon(IconNames.Yes)
    robotbit.Servo(robotbit.Servos.S8, 0)
    robotbit.Servo(robotbit.Servos.S1, 0)
    basic.pause(5000)
    robotbit.Servo(robotbit.Servos.S8, 90)
    robotbit.Servo(robotbit.Servos.S1, 90)
    basic.pause(2000)
    robotbit.Servo(robotbit.Servos.S8, 180)
    robotbit.Servo(robotbit.Servos.S1, 180)
    basic.pause(5000)
    robotbit.Servo(robotbit.Servos.S8, 90)
    robotbit.Servo(robotbit.Servos.S1, 90)
})
input.onButtonPressed(Button.B, function () {
    basic.showIcon(IconNames.No)
    robotbit.Servo(robotbit.Servos.S8, 90)
    robotbit.Servo(robotbit.Servos.S1, 90)
})
basic.showIcon(IconNames.Heart)
let strip = neopixel.create(DigitalPin.P16, 4, NeoPixelMode.RGB)
strip.showRainbow(1, 360)
basic.pause(1000)
strip.showColor(neopixel.colors(NeoPixelColors.Black))
basic.pause(1000)
strip.showColor(neopixel.colors(NeoPixelColors.Black))
basic.forever(function () {
	
})
